{
 "title": "JVM dashboard",
 "description": "Complete dashboard using metrics from Prometheus JMX exporter, with drill down based on JMX Prometheus jobs",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "java_app_jmx" },
   { "name": "instance", "label": "instance", "query": "spring-app-jmx:9404" },
   {
    "name": "mempool",
    "query": "label_values(jvm_memory_pool_bytes_max{job=\"$job\", instance=\"$instance\"}, pool)"
   },
   {
    "name": "memarea",
    "query": "label_values(jvm_memory_bytes_used{job=\"$job\", instance=\"$instance\"}, area)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"$job\",instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "System load average",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "os_system_load_average{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Available CPUs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_available_processors{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "os_open_file_descriptor_count{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "os_system_cpu_load{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "System"
    },
    {
     "expr": "os_process_cpu_load{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "JVM"
    }
   ]
  },
  {
   "title": "Memory area [$memarea]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\",job=\"$job\",instance=\"$instance\"} / jvm_memory_bytes_max >= 0",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{job=\"$job\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Memory pool [$mempool]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "repeat": "mempool",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{pool=\"$mempool\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_used_bytes{pool=\"$mempool\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{pool=\"$mempool\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_total{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "GC count increase",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{job=\"$job\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "JVM current threads"
    },
    {
     "expr": "jvm_threads_daemon{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "JVM daemon threads"
    },
    {
     "expr": "jvm_threads_deadlocked{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "JVM deadlocked threads"
    }
   ]
  },
  {
   "title": "Physical memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "os_total_physical_memory_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Total physical memory"
    },
    {
     "expr": "os_committed_virtual_memory_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Committed virtual memory"
    },
    {
     "expr": "os_free_physical_memory_bytes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Free physical memory"
    }
   ]
  }
 ]
}